# Generated by Django 2.2.5 on 2019-10-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name_plural': 'Records'},
        ),
    ]
