# Generated by Django 2.2.5 on 2019-10-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191017_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='education',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bio',
            new_name='Introduction',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='country',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='occupation',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='records',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='records',
            name='residence',
        ),
    ]
