# Generated by Django 2.2.5 on 2019-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20191018_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='Picture',
            field=models.ImageField(default='', upload_to='Records/%Y/%m'),
        ),
    ]
