# Generated by Django 2.2.5 on 2019-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_records_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Picture',
            field=models.ImageField(default='', upload_to='', verbose_name='id'),
        ),
    ]
