# Generated by Django 2.2.5 on 2019-10-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20191019_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Picture',
            field=models.ImageField(default='', upload_to='id'),
        ),
    ]
