# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-12 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20191112_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='Picture_path',
        ),
    ]
